# Generated by Django 3.2 on 2024-06-16 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Web', 'Web'), ('Cloud', 'Cloud')], max_length=50)),
                ('cover_image', models.ImageField(upload_to='portfolio/peter/')),
                ('description', models.TextField()),
                ('project_url', models.URLField()),
                ('github_url', models.URLField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
